server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name:
      msvc-gateway
    cloud:
      gateway:
        discovery:
          locator:
            enable:
        routes:
          - id : aluno
            uri: http://localhost:8090
            predicates:
              - Path=/api/aluno/**
